name: Deploy via ftp

on: push

jobs:

  deploy:

    name: Deploy

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2




    - name: FTP Deploy Locaweb

      uses: locaweb/ftp-deploy@1.0.0

      with:

        host: ${{ ftp.instrutorzonasulsp.com.br }} 

        user: ${{ instrutorzonasul1 }}

        password: ${{ Collato@042026 }}

        localDir: "./leopoldo-collato
Instrutor-veicular-Zona-Sul-SP"

        remoteDir: ".//home/instrutorzonasul1/public_html/"
